### ISSUE TITLE
App turns itself back on when disabled in accessibility settings.

### ISSUE THREAD

**Issue by Theguysayhi** [tribalfs/GalaxyMaxHzPub#10]
When the app is toggled off in accessibility (so I can gain access to my controller and Google Chrome) the app turns itself on again and disables external inputs again on my Galaxy Fold 3.

This is a pretty big issue for me and I may have to Uninstaller as a result, which is a shame bethe app works well standalone and in tasker otherwise. I really hope that this is fixed in the future!

**Comment by tribalfs** [comment]
- v7.14.16 fixed bug: unable to turn off accessibility when no feature requiring such is enabled.
- controller access  is an android issue - fixed in android 12.
