### ISSUE TITLE
Donation\Premium code says invalid code

### ISSUE THREAD

**Issue by SahiDemon** [tribalfs/GalaxyMaxHzPub#100]
I recently downloaded and used the free trail of Galaxymax Hz and i purchased after. But activation code is not working it says invaid code.

**Comment by tribalfs** [comment]
Hi! Please email us your activation code so we can check it.
Thank you.

Best regards,
tribalfs

**Comment by SahiDemon** [comment]
Thanks issue is fixed great app btw
