### ISSUE TITLE
Galaxy M12: Per-app setting crashing or loading slowly.

### ISSUE THREAD

**Issue by Sahil12524** [tribalfs/GalaxyMaxHzPub#101]
The Per-app setting option sometimes crashes the whole app or sometimes loading the list very slowly, app not responding!

Kindly fix the issue as it not a major issue.

Version that I am using is v8.1.9 beta channel.

**Comment by tribalfs** [comment]
Please specify device, and which specific app in the list causes crash. Thank you.

**Comment by Sahil12524** [comment]
My Device is Samsung M12 127G.
I don't exactly know which app in the list cause it.
but when I click on Per-app Settings it loads very slowly or some times even crashes!

**Comment by tribalfs** [comment]
Please check v8.1.10 update.
