### ISSUE TITLE
Galaxy M12: Per-app settings not working on games

### ISSUE THREAD

**Issue by Sahil12524** [tribalfs/GalaxyMaxHzPub#102]
When I set my refresh rate mode on Adaptive and then play the games, the games works on 60Hz only.
When I switch the mode to Constant High the game works on 90Hz.
So I decided to use Adaptive mode and Per-app Settings for the games to stay at Static 90Hz but it doesn't works on games, the game still works on 60Hz only.
Possible fixes can be like 'Force the Game Optimization Service to 90Hz Static' or 'Force the Game Booster to 90Hz'.

See if we can disable or uninstall the app using ADB, we can do the same with those apps too.

**Comment by tribalfs** [comment]
Which game and what device?

**Comment by Sahil12524** [comment]
Every apps that is recognized as a game by Game Optimization Service (GOS).
Device: Samsung M12 127G

**Comment by tribalfs** [comment]
But I am unable to replicate it on my test devices (S22U and Note20 U)

**Comment by Sahil12524** [comment]
Can you try it on some low-end devices like M, A, F series?, who has 90Hz refresh rate only.

**Comment by caingatcarl** [comment]
> Which game and what device?

Mine also. Samsung S22+ and the game is DMC Peak of Combat. Static 120hz not working on per app settings. Still locked at 60hz

**Comment by Sahil12524** [comment]
> > Which game and what device?
> 
> Mine also. Samsung S22+ and the game is DMC Peak of Combat. Static 120hz not working on per app settings. Still locked at 60hz

mostly this app should make the GOS think its static, then only the game will work as static, I hope!
