### ISSUE TITLE
Camera app problem

### ISSUE THREAD

**Issue by magixman1** [tribalfs/GalaxyMaxHzPub#106]
When Galaxy MaxHz is on the camera app can't be launched. "System privacy settings are preventing app from launch". S22+ Android 13 OneUi 5.1.

**Comment by tribalfs** [comment]
Can you provide more details?
We don't experience that issue in our Samsung devices running on OneUI5.1 (S22Ultra, Note20Ultra and S1+).
Seems other things causes it which is peculiar to your device.  It's  first time that we receive this issue.

**Comment by magixman1** [comment]
It's happening when the button "sensors off" is activated .

**Comment by magixman1** [comment]
Switching on button "sensors off" causing that. 
![Screenshot_20230527_010855_One UI Home](https://github.com/tribalfs/GalaxyMaxHzPub/assets/28996195/c38cbecc-ce0d-478c-a9d9-c1968bc0758e)
![Screenshot_20230527_010734_Files](https://github.com/tribalfs/GalaxyMaxHzPub/assets/28996195/55d7f775-e762-43c4-9b4e-58afd9fdb6be)

**Comment by tribalfs** [comment]
That's expected. That's how Sensors off  work.
