### ISSUE TITLE
Screen stuck in 60hz when set to 96hz

### ISSUE THREAD

**Issue by AlvaroBuelvas** [tribalfs/GalaxyMaxHzPub#110]
I want to report that if I set the max refresh rate to 96hz, it will sometimes be stuck in 60hz in a low light environment.

To reproduce:
 While being in a well lit environment and manually decreasing the brightness, it will actually go to 96hz.

Then, if I cover the light sensor with my hand, it is at that point where the screen will be stuck at 60hz.

So it seems that this issue triggers only when both the brightness is low and light sensor doesn't get much light.

I can continuously see how it goes between 60 and 96hz by covering and uncovering the light sensor, while the brightness is at the lowest.

This happens without any other mods ot setting being applied. Device in normal mode. Not in power saving.

Device: Samsung s23 ultra - SM-S918B

Im running One UI 5.1 and the app version is 8.1.10

**Comment by tribalfs** [comment]
This is actually indicated in in-app info.
Please check [this ](https://forum.xda-developers.com/t/app-galaxy-max-hz-refresh-rate-mods-screen-off-mods-qs-tiles-tasker-support-and-more.4549351/post-88164313)and [this](https://forum.xda-developers.com/t/app-galaxy-max-hz-refresh-rate-mods-screen-off-mods-qs-tiles-tasker-support-and-more.4549351/post-88164369).
