### ISSUE TITLE
SM-G780G: Issues with the donation app

### ISSUE THREAD

**Issue by voaneves** [tribalfs/GalaxyMaxHzPub#111]
**Describe the bug**
I've already paid the donation once on the same device, but it's asking me to donate again after a wipe. My e-mail is victorneves478@gmail.com

**To Reproduce**

A. GMH version and the exact settings in GMH
v8.1.1, Donation app from the play store.

B. Steps to reproduce the behavior:
1. Download the donation app;
2. It's asking to pay again.

**Expected behavior**
It should automatically recognize that I'm on the same phone.

**Smartphone (please complete the following information):**
 - Model Number: [e.g. SM-S908B] SM-G780G
 - OS/OneUI version:  [e.g. android12 OneUI4.1] OneUI 5.1
 - Date of latest security update, if applicable: [e.g. June 2022] May 2023
 - Stock or modded ROM? Stock

**Comment by tribalfs** [comment]
Please check [FAQ # 2](https://github.com/tribalfs/GalaxyMaxHzPub/wiki/Frequently-Asked-Questions-(FAQs)#2-i-could-not-find-activation-code-email-in-my-inbox-or-i-forgot-to-backup-my-activation-code-what-should-i-do)

**Comment by voaneves** [comment]
Thanks!
