### ISSUE TITLE
S21U, After restart phone goes to standard 60hz and not adaptive but set to constant.

### ISSUE THREAD

**Issue by AmirulAndalib** [tribalfs/GalaxyMaxHzPub#116]
Hi @tribalfs 

Thanks for this awesome project and app. But I have an issue with my S21Ultra that is when I reboot my phone, It resets to standard 60hz and not constant 120hz which was set by me. Is there any fix for this?

Thanks.
![Screenshot_20230820_031701_Galaxy MaxHz](https://github.com/tribalfs/GalaxyMaxHzPub/assets/86344856/a1fac91b-c55a-45c6-b60e-a51da7c28ee7)

**Comment by tribalfs** [comment]
Hi! Are you on a stock rom?
Because it's strange specially that your device is not on power saving mode. 
The app doesn't change the refresh rate mode when device is rebooted.
I also double-checked with my devices but unable to replicate it.

**Comment by AmirulAndalib** [comment]
> Hi! Are you on a stock rom? Because it's strange specially that your device is not on power saving mode. The app doesn't change the refresh rate mode when device is rebooted. I also double-checked with my devices but unable to replicate it.

it is a stock modified rom called BeyondROM

**Comment by AmirulAndalib** [comment]
> Hi! Are you on a stock rom? Because it's strange specially that your device is not on power saving mode. The app doesn't change the refresh rate mode when device is rebooted. I also double-checked with my devices but unable to replicate it.

any setting I missed?

**Comment by tribalfs** [comment]
Shouldn't be affected  by any of the app settinga. 
Try to clear app data.

**Comment by AmirulAndalib** [comment]
It seems that MaxHZ had a lsposed module which wasnt enable from the lsposed manager. I think it should work as expected now...

![Screenshot_20230822_210227_LSPosed](https://github.com/tribalfs/GalaxyMaxHzPub/assets/86344856/61c7e3d2-0f07-44f0-a246-6065d1f1d07c)
