### ISSUE TITLE
Adaptive Refreshrate (ARR) 60-120 not working at v8.1 on my Galaxy Z Flip 3 5G

### ISSUE THREAD

**Issue by karls0r** [tribalfs/GalaxyMaxHzPub#118]
Descirption: 
First of all: great job. Loving the app, just got premium just to give you the credits for this one. 
I'm german and using the german app, so the descriptions from me could be having problems when translated the words from german, but probably you'll understand what I mean. 

The Bug: 
- when being on adaptive refreshrate setting to a range from 48 to anwhere (either 120 or 96), everything is working fine

- when setting it to the range from 60-96 or 120, it just stays on 120 all the time. 

I especially noticed on youtube premium, I wanted to check if the adaptive refreshrate works when setting it globally. It does on the above described mode, but not if anything is set to 60-120. I noticed it while I wanted to have my ARR set for only youtube being adaptive from 60hz-120hz, but noticed when setting this up it will only stay on 120hz. 
Then I tried to change the global ARR Setting to 60-120, and noticed that it will stay at only 120hz all the time (not only YouTube)

**To Reproduce**

A. GMH version: 8.1,  | Settings: FHD+ on ADAPTIVE (Normal: 48-120, Safemode: 48-60, Battery Low: 48-60), Fast-Setting on, Screenoff on (48hz), Energy-Safemode when Screen turned off, the rest is turned off)

B. Steps to reproduce the behavior:
1. Go to Refreshrates in Adaptive Mode
2. Choose 60 Hz as lowest and any higher value for highest.
3. Watch Refreshrate with either your Notification-App-Thingy or inbuilt Refreshrate-Shower (Developersmode)

1. Go to ''per App''
2. Look for Youtube
3. Choose adaptive and set it to 60hz as the lowest and any higher value at the highest ARR. 

Expected behavior;
Expecting the YouTube App being limited to 60hz after not tapping on screen, but it doesnt.

Screenshots:
Doesnt really do much, I wanted to make a screen recording, but it's gonna limit itself to 60 hz when starting the recording. 

Samsung Galaxy Z Flip 3 5G
 - Model Number: [e.g. SM-F711B
 - OS/OneUI version:  Android 13, One UI 5.1.1
 - Date of latest security update: September 2023
 - Stock Rom

Additional Context: 

I realized also that on my YouTube Premium when I do PIP on my Screen with the video, the ARR just stays at 120hz, when killing the YT PIP Player, it behaving as wanted and changing to 48hz when not tapping anywhere.

**Comment by tribalfs** [comment]
Please use the app to screen record:
https://play.google.com/store/apps/details?id=us.rec.screen

**Comment by tribalfs** [comment]
Please note that the 60-120 or 60-96 settings is just using the stock adaptive algorithm.

**Comment by tribalfs** [comment]
Tried to replicate it with a Note20 Ultra device with same refresh rate profile as the Z Flip 3 but unable to replicate it.

**Comment by karls0r** [comment]
Aha, …maybe it just seems like my phone doesnt work the way it should work in general.. when i turn off your settings, it will stay at 120hz all the time, not even doing the stock adaptive things… 😲 

ill check out the video recording tool and then gonna send it to you !

 

Von: Tribalfs ***@***.***> 
Gesendet: Donnerstag, 21. September 2023 22:46
An: tribalfs/GalaxyMaxHzPub ***@***.***>
Cc: karls0r ***@***.***>; Author ***@***.***>
Betreff: Re: [tribalfs/GalaxyMaxHzPub] Adaptive Refreshrate (ARR) 60-120 not working at v8.1 on my Galaxy Z Flip 3 5G (Issue #118)

 

Please note that the 60-120 or 60-96 settings is just using the stock adaptive algorithm.

**Comment by tribalfs** [comment]
Maybe you set your brightness too low?

**Comment by karls0r** [comment]
So weird, now everything works just fine and as intended. 
yeah, it could be the brightness, i didnt know it would affect the behavior of the apps functionallity.. 

thanks for reaching out so fast tho <3
