### ISSUE TITLE
Automatic language selection

### ISSUE THREAD

**Issue by Steffe2** [tribalfs/GalaxyMaxHzPub#12]
An option to be able to select the language you want would be nice. 
As it is now, it automatically chooses Swedish for me. And that translation is horrible, and has mixed languages in the interface.

**Comment by tribalfs** [comment]
That can't be implemented on GMH.
It's possible but it's not a standard in android. it will add much overhead
to the app.

What we can do instead is introduce corrections to Swedish strings. Are you
willing to contribute?

Thank you.

**Comment by Steffe2** [comment]
I could definitely take a look at least. Although I usually prefer special apps, like this, in English.
Been helping with some apps and games before though 😊

Weird that it can't be added easily though. Since it's already changing some strings into Swedish automatically (it'd "just" be a selector instead of automatic).

**Comment by tribalfs** [comment]
Swedish translation improvement implemented.
Thank you for your help.
