### ISSUE TITLE
anti flicker - feature request

### ISSUE THREAD

**Issue by sungruhyun** [tribalfs/GalaxyMaxHzPub#120]
It would be nice to add the ability to reduce flickers like OLED SAVER, XIAOMI Anti-Flicker Mode.

**Comment by tribalfs** [comment]
Sorry, this needs to be done on kernel level. I don't even know if it's possible on samsung which is using PWM. I am not a kernel developer.

**Comment by sungruhyun** [comment]
OLED SAVER is an app that can be used by Samsung It works on the principle of maximizing the brightness setting of the device and lowering the brightness using a filter

**Comment by tribalfs** [comment]
Oh.. not a true DC dimming like in Xiaomi but a clever workaround for PWM using transparent overlay. But also a battery drainer I believe since it needs to maintain max brightness all the time.
