### ISSUE TITLE
Update Not Possible

### ISSUE THREAD

**Issue by drewauff** [tribalfs/GalaxyMaxHzPub#130]
GalaxyMaxHz stopped working after OneUI 6 update.

Followed instructions to get it working.

Upon 1st run am told a new update is available. So I tried to update but message popups up stating my S23 Ultra is not compatible with this new version and can't be installed.

Is this somehow my own fault? or a bug in the app?

**Comment by tribalfs** [comment]
It's expected in OneUI6.0 due to the restrictions it introduced for apps targeting low sdk.
Installing and updating the app now needs to be done using ADB as indicated [here](https://github.com/tribalfs/GalaxyMaxHzPub/releases/tag/v8.1).
