### ISSUE TITLE
One ui 6 isse

### ISSUE THREAD

**Issue by RashadGasimly** [tribalfs/GalaxyMaxHzPub#132]
**Important: Before submitting a bug, ensure to check [FAQs](https://github.com/tribalfs/GalaxyMaxHzPub/wiki/FREQUENTLY-ASK-QUESTIONS-(FAQs))  and in the app description in the appropriate XDA forum thread for your device to ensure that the behavior is not expected or not part of the limitation of the app.**

**Describe the bug**
Hello, I saw that there is a new update but when i tap the "update" button it says "starting one ui 6, the app can only be installed using adb", but i'm on one ui 5.1 not one ui 6.

**To Reproduce**

A. GMH version is v8.1.26

B. Steps to reproduce the behavior:

**Expected behavior**

**Screenshots**
If applicable, please include screenshots and/or [screen recording](https://play.google.com/store/apps/details?id=us.rec.screen) to help explain your problem. 
![Screenshot_20231213_001236_Galaxy MaxHz](https://github.com/tribalfs/GalaxyMaxHzPub/assets/129990317/822fff0c-e3ac-4dcc-a5fb-b7704f052673)
![Screenshot_20231213_001739_Settings](https://github.com/tribalfs/GalaxyMaxHzPub/assets/129990317/49ab3adc-94ec-4284-96f8-2a039400779e)

**Smartphone (please complete the following information):**
 - Model Number: SM-A525F/DS
 - OS/OneUI version:  Android 13/One UI 5.1
 - Date of latest security update, if applicable: 1 November 2023
 - Stock or modded ROM?: Modded ROM

**Additional context**

**Crashlog**
If GMH crashes on your device, please include the crashlog of your device.  Just execute the following adb command. 
`adb logcat -c`.  
Then reproduce the crash.   Then execute this right after the crash (device must not be rebooted yet):
`adb logcat -b crash > crashlog.txt`
_Ctrl+C_ after 10seconds.
Then locate _crashlog.txt_ file in your adb installation folder then send it to tribalfs@gmail.com.

**Comment by tribalfs** [comment]
Please check instructions for OneUI6.0
https://github.com/tribalfs/GalaxyMaxHzPub/releases/tag/v8.1
