### ISSUE TITLE
Refresh monitor not working for me

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [tribalfs/GalaxyMaxHzPub#133]
**Important: Before submitting a bug, ensure to check [FAQs](https://github.com/tribalfs/GalaxyMaxHzPub/wiki/FREQUENTLY-ASK-QUESTIONS-(FAQs))  and in the app description in the appropriate XDA forum thread for your device to ensure that the behavior is not expected or not part of the limitation of the app.**

**Describe the bug**
I just updated my device to OneUI 6 and GMH said there was an update. It says it couldn't update so i used the adb method to install it. I also typed in write secure settings just in case. When I try to enable it now, it disables automatically.

**To Reproduce**

A. GMH version and the exact settings in GMH
v8.1.27

B. Steps to reproduce the behavior:
1. Open GMH
2. Go to Refresh rate monitor
3. Enable it
4. Click on Refresh rate monitor
5. It's turned off.

**Expected behavior**
It should be kept enabled.

**Screenshots**
If applicable, please include screenshots and/or [screen recording](https://play.google.com/store/apps/details?id=us.rec.screen) to help explain your problem. 

**Smartphone (please complete the following information):**
 - Model Number: [e.g. SM-S908B]
 - OS/OneUI version:  [e.g. android12 OneUI4.1]
 - Date of latest security update, if applicable: [e.g. June 2022]
 - Stock or modded ROM?

SM-X900
Android 14 OneUI 6
November 2023
Stock

**Additional context**

**Crashlog**
If GMH crashes on your device, please include the crashlog of your device.  Just execute the following adb command. 
`adb logcat -c`.  
Then reproduce the crash.   Then execute this right after the crash (device must not be rebooted yet):
`adb logcat -b crash > crashlog.txt`
_Ctrl+C_ after 10seconds.
Then locate _crashlog.txt_ file in your adb installation folder then send it to tribalfs@gmail.com.

**Comment by tribalfs** [comment]
Please read:
https://github.com/tribalfs/GalaxyMaxHzPub/releases/tag/v8.1
