### ISSUE TITLE
Adb command do not working

### ISSUE THREAD

**Issue by GabrielWeasel** [tribalfs/GalaxyMaxHzPub#141]
I'm following exactly the steps from the tutorial and the video to install galaxy max hz on Android 14. After moving GMH to the root, I paste the adb code and it shows me: 

/system/bin/sh: <stdin>[1]: adb: inaccessible or not found

I'm using the version without PC: adb install --bypass-low-target-sdk-block /sdcard/galaxy_max_hz_v8.1.apk

Yes, I'm making the step to step correctly. Am I making something wrong?

![Screenshot_20231221_235509_LADB](https://github.com/tribalfs/GalaxyMaxHzPub/assets/154571442/1814897f-1f42-4af0-bb59-e9519132290c)

**Comment by tribalfs** [comment]
Please read or watch the guide carefully. You should use "adb shell" mode in LADB not "non-adb shell" mode. The latter is triggered when you skip pairing. You can turn it on again in LADB settings.
