### ISSUE TITLE
Adaptive framerate not applied after restart or after switcihng power saving mode on/off

### ISSUE THREAD

**Issue by LoneDev6** [tribalfs/GalaxyMaxHzPub#151]
**Describe the bug**
At some point I see that the adaptive refreshrate is not applied, instead I get 48-60hz.
My adaptive refreshrate setting is 120/96/60/48hz.
This seems to happen on phone restart and on powersaving mode on/off switching.

Is this a known issue?

**To Reproduce**

GMH version and the exact settings in GMH:
8.1.28

1. This seems to happen on phone restart and on powersaving mode on/off switching.
2. Adaptive refreshrate is not applied and reset to a lower than 120hz value.

**Expected behavior**
Have the correct high refreshrate set.

**Smartphone (please complete the following information):**
 - Model Number: SM-G991B/DS
 - OS/OneUI version: Android 14, OneUI 6.0
 - Date of latest security update, if applicable: Jan 1, 2024
 - Stock or modded ROM: Stock

**Comment by tribalfs** [comment]
Yes, it's expected as [extra steps](https://github.com/tribalfs/GalaxyMaxHzPub#:~:text=Devices%20with%20OneUI5%2B%20and%20those%20few%20with%20OneUI4.*%20require%20extra%20steps3%20except%20when%20rooted%20with%20Magist%20and%20LSPosed%20module%20installed.) are needed if power saving mode is toggled.
