### ISSUE TITLE
Lag in animations during 120hz _ 60hz transition when I open apps in per-app settings mode

### ISSUE THREAD

**Issue by Y4d13l** [tribalfs/GalaxyMaxHzPub#154]
In future updates to the GalaxyMaxHz application I would like them to add a minimum Hz delay for the configuration mode per application, so that there is an estimated time necessary for the opening animation to be at 120 Hz and after the application is 100% open change to 60 Hz, this eliminates the annoying lag that appears when opening applications just when you change from 120 Hz to 60 Hz, with an adequate delay this can be fixed. I hope you take it into account. Greetings. Great job.

**Comment by tribalfs** [comment]
We implemented the down-shifting delay in the latest version. 
Please install the latest version (v8.1.28) if you haven't yet.
You can download the latest version here:
https://github.com/tribalfs/GalaxyMaxHzPub/releases/tag/v8.1
