### ISSUE TITLE
App not compatible with Samsung S22 Ultra

### ISSUE THREAD

**Issue by labibhere2000** [tribalfs/GalaxyMaxHzPub#156]
Hey everyone.
I am having issues while installing the apk file on my Samsung s22 Ultra. It says this app isn't compatible with my phone.

I have bought the donation version and now i am unable to use the app.

Can somebody help me installing the app? 

![Screenshot_20240306_215619_Package installer](https://github.com/tribalfs/GalaxyMaxHzPub/assets/145862669/bef40925-d50c-4f7f-9f20-fa1801709685)

**Comment by tribalfs** [comment]
Pls read and follow installation instructions:

https://github.com/tribalfs/GalaxyMaxHzPub/releases/tag/v8.1

**Comment by tribalfs** [comment]
Please follow instructions for oneui6 here:
https://github.com/tribalfs/GalaxyMaxHzPub/releases/tag/v8.1

Best regards,
Tribalfs
