### ISSUE TITLE
10Hz doesn't work with AOD on S23+ 

### ISSUE THREAD

**Issue by bkdwt** [tribalfs/GalaxyMaxHzPub#160]
**Describe the bug**
10Hz is not working on AOD. Still 24Hz. Sometimes stop working at 10Hz on general and stay on 24Hz minimum.

**To Reproduce**

A. 8.1.29
MEdE, MdEN and BF set to 10 - 120Hz and low brightness set to any value (10% on my case)

**Expected behavior**
AOD workin at 10Hz instead the minimum 24Hz.

**Smartphone (please complete the following information):**
 - Model Number: SM-S916B
 - OS/OneUI version: Android 14 ONE UI 6
 - Date of latest security update, if applicable: February 1st
 - Stock or modded ROM? Stock

**Comment by tribalfs** [comment]
Hi!
Did you[ allow restricted settings to the app](https://github.com/tribalfs/GalaxyMaxHzPub/releases#:~:text=After%20install%20and,is%20already%20shown.)?

**Comment by bkdwt** [comment]
> Hi! Did you[ allow restricted settings to the app](https://github.com/tribalfs/GalaxyMaxHzPub/releases#:~:text=After%20install%20and,is%20already%20shown.)?
> 
> Also try to check it using the refresh rate monitor in the developer option instead of using the one in the app (related info in [faq #11](https://github.com/tribalfs/GalaxyMaxHzPub/wiki/Frequently-Asked-Questions-(FAQs)#11--the-show-refresh-rate-tool-found-in-developer-option-shows-faster-switching-down-of-refresh-rate-when-compared-to-what-is-shown-in-the-apps-refresh-rate-monitor-why))

Yeah, both options.

**Comment by tribalfs** [comment]
Does 10hz works on S23+ while screen is on (when setting min hz to 10Hz)?

**Comment by tribalfs** [comment]
Please update to [v8.1.30 ](https://github.com/tribalfs/GalaxyMaxHzPub/releases/tag/v8.1#:~:text=Latest%20Build%3A%20v8.1.30)

**Comment by bkdwt** [comment]
> Please update to [v8.1.30 ](https://github.com/tribalfs/GalaxyMaxHzPub/releases/tag/v8.1#:~:text=Latest%20Build%3A%20v8.1.30) Thank you.

Now are working. Thanks so much! 😊
