### ISSUE TITLE
AOD always on 120hz

### ISSUE THREAD

**Issue by Xisrr1** [tribalfs/GalaxyMaxHzPub#167]
Is it a bug?

**Comment by tribalfs** [comment]
What version do you have? Did you check it using the refresh rate from the developer options?

**Comment by Xisrr1** [comment]
The latest version, 8.1, and I checked with the refresh rate monitor.

**Comment by tribalfs** [comment]
Use the one from developer option to check

**Comment by Xisrr1** [comment]
Yes, I'm using this version. AOD is on 120hz. I checked several times.

**Comment by tribalfs** [comment]
What device is this?

**Comment by Xisrr1** [comment]
Yes

**Comment by Xisrr1** [comment]
Yes

**Comment by Xisrr1** [comment]
I think GMH failes to switch the refresh rate when the screen is off.

**Comment by tribalfs** [comment]
It does actually changed but seems the refresh rate monitor does not update immediately anymore on AOD, not until the AOD shifts position (try to wait until it shifts position).

You can also check it using ADB command while on AOD/screen off:
`adb shell settings get system peak_refresh_rate`
