### ISSUE TITLE
Brightness threshold no longer works on 8.1.50

### ISSUE THREAD

**Issue by Xisrr1** [tribalfs/GalaxyMaxHzPub#174]
**Important: Before submitting a bug, ensure to check [FAQs](https://github.com/tribalfs/GalaxyMaxHzPub/wiki/FREQUENTLY-ASK-QUESTIONS-(FAQs))  and in the app description in the appropriate XDA forum thread for your device to ensure that the behavior is not expected or not part of the limitation of the app.**

**Describe the bug**
Not disabling adaptive refresh rate when below threshold. 

**To Reproduce**

A. GMH version 8.1.50

B. Steps to reproduce the behavior:
1. Use brightness threshold.
2. It doesn't work.

**Expected behavior**
Disabling adaptive mode when below threshold. 

**Smartphone (please complete the following information):**
 - Model Number: SM-A536B
 - OS/OneUI version:  Android 14, OneUI 6.0
 - Date of latest security update, if applicable: March 2024.
 - Stock or modded ROM? Stock.

**Additional context**

**Crashlog**
If GMH crashes on your device, please include the crashlog of your device.  Just execute the following adb command. 
`adb logcat -c`.  
Then reproduce the crash.   Then execute this right after the crash (device must not be rebooted yet):
`adb logcat -b crash > crashlog.txt`
_Ctrl+C_ after 10seconds.
Then locate _crashlog.txt_ file in your adb installation folder then send it to tribalfs@gmail.com.

**Comment by tribalfs** [comment]
Indeed a bug. I messed up  a stateflow flag. 
Please update to [v8.1.51](https://github.com/tribalfs/GalaxyMaxHzPub/releases/download/v8.1/galaxy_max_hz_v8.1.apk) for the hotfix.

Thank you.

**Comment by Xisrr1** [comment]
What about the 60hz on AOD still doesn't work?
