### ISSUE TITLE
Adaptive mode and notification panel

### ISSUE THREAD

**Issue by aiko-chan-ai** [tribalfs/GalaxyMaxHzPub#175]
**Describe the bug**
I noticed that when clearing/swiping notifications, the refresh rate seems to drop to 60hz when in adaptive mode.

**To Reproduce**

A. GMH version: 8.1.30

B. Steps to reproduce the behavior:
- Use adaptive mode
- When there are many notifications, swiping the notification will decrease to 60hz

**Expected behavior**
Refresh rate up to 120hz

**Smartphone (please complete the following information):**
 - Model Number: SM-G990U
 - OS/OneUI version: Android 14 OneUI 6
 - Date of latest security update, if applicable: March 2024
 - Stock or modded ROM? Stock

**Additional context**
The error occurs randomly, idk if others have the same problem or not

**Comment by aiko-chan-ai** [comment]
It seems like the error is gone when on the home screen but remains on the lock screen
While on the lock screen, open the notification panel, select any notification, then swipe gently and hold still (wait for the screen to decrease to 60hz), this time when you swipe it will still be 60hz
(my english isnt good)

**Comment by tribalfs** [comment]
Yeah, unfortunely this is limitatoin which is due lack of api that can be used to detect  prolonged gestures on notification panel

**Comment by aiko-chan-ai** [comment]
Thanks for your information <3
