### ISSUE TITLE
Net Speed Indicator keeps changing its size every second(and gets cut off)

### ISSUE THREAD

**Issue by vpsj** [tribalfs/GalaxyMaxHzPub#176]
I am noticing that the Internet Speed Indicator keeps getting part of it cut off because its font keeps changing size. I think it's better to show you a small screen recording to explain the issue properly:

https://github.com/tribalfs/GalaxyMaxHzPub/assets/8344040/5a7e99a5-e22c-4f09-bf7d-7f5fbe3b2ae1

PS: I know the 'screen recorder' icon is present here but even without it the behavior is still the same.

It _could_ be because of the font size I have selected for my phone's system, but honestly the speed indicator still seems to be changing it font every second which in my opinion shouldn't be happening.

Is this a known bug? I did search for it and didn't find anything. Any ideas on fixing it? Or any explanation for why does it keep alternating between two different font sizes? Please let me know. Thanks!

Note: Speed indicator is the only feature I use from GMH, everything else is kept at default setting.

**To Reproduce**
A) Use the latest version of GMH (v8.1)

B) Steps to reproduce the bug: 
Just run the speed indicator and start downloading something.

**Expected behavior**
The speed indicator should stay the same size and should not get cut off every second.

**Smartphone (please complete the following information):**
 - Model Number: S23Ultra
 - OS/OneUI version:  OneUI 6.1 
 - Date of latest security update - April security update.

**Comment by tribalfs** [comment]
You mean v8.1.50/60?

I don't noticed this cut-off issue on my devices. 

Are you using a custom font?

https://github.com/tribalfs/GalaxyMaxHzPub/assets/65062033/2885142a-65d2-4e32-908d-839cd6cb33b2

**Comment by vpsj** [comment]
I am using the Roboto font which as far as I know is the default.

BUT, I think I figured out the reason: I saw the DND icon in your video which gave me the clue: It's missing from mine even though I keep DND on 24/7. 

Then I realized that I use autonotification to hide the DND notification (because it's persistent and annoying), which also hides that icon but that was the one causing the changes in the fonts and the cut off.

Doesn't seem like it's an issue with GMH (I'll take this up with the tasker guy). You can close this and mark it resolved. 

Thank you for checking it out!
