### ISSUE TITLE
after 8.1.75, app crash on OneUi3.1

### ISSUE THREAD

**Issue by rkselrkswm5** [tribalfs/GalaxyMaxHzPub#181]
**Describe the bug**
I was using the version before 8.1.75 well, but today I updated to 8.1.75 through the max hz app, but when I run the app, it closes immediately. A force shutdown error appears.

Version 8.0 works fine.

A. GMH version and the exact settings in GMH
8.1.75

**Smartphone (please complete the following information):**
 - Model Number: SM-G981N
 - OS/OneUI version:  One UI 3.1, Android 11
 - Date of latest security update, if applicable:  2021, August 1st.
 - Stock or modded ROM? Stock(original rom)

**Crashlog**
If GMH crashes on your device, please include the crashlog of your device.  Just execute the following adb command. 
`adb logcat -c`.  
Then reproduce the crash.   Then execute this right after the crash (device must not be rebooted yet):
`adb logcat -b crash > crashlog.txt`
_Ctrl+C_ after 10seconds.
Then locate _crashlog.txt_ file in your adb installation folder then send it to tribalfs@gmail.com.

**Comment by tribalfs** [comment]
Hi! Can you provide a crashlog? Thanks.

**Comment by tribalfs** [comment]
Got it. Thank you.

**Comment by rkselrkswm5** [comment]
Thanks for update.
It works well now.
