### ISSUE TITLE
No adaptive option

### ISSUE THREAD

**Issue by Xisrr1** [tribalfs/GalaxyMaxHzPub#182]
![Screenshot_20240426_140635_Galaxy MaxHz.jpg](https://github.com/tribalfs/GalaxyMaxHzPub/assets/133952156/75ba41f1-b9f0-4919-99fa-649f42b62597)

**Comment by tribalfs** [comment]
Did you activate premium?

**Comment by Xisrr1** [comment]
No. It's like that even on a fresh install

**Comment by tribalfs** [comment]
I believe the free trial is used up.

**Comment by Xisrr1** [comment]
Yes it's used up. I don't want to sound weird but I could usually reinstall to get another 2 days...

**Comment by Princeofpersiattt** [comment]
So adaptive option is now moved into premium features.

**Comment by tribalfs** [comment]
Adaptive Mod has always been  premium feature. Please check app description.
