### ISSUE TITLE
Per-app settings not applying on youtube and newpipe (S20FE OneUi5.1)

### ISSUE THREAD

**Issue by Dimon245** [tribalfs/GalaxyMaxHzPub#188]
**Describe the bug**
Per-app settings doesn't work. I set NewPipe and YouTube to constant 60 hz and it doesn't switch to that. It used to work before the latest stable update

**To Reproduce**

A. 8.1.75. Per-app settings - YouTube and NewPioe at 60 hz

**Expected behavior**
When you go to any app set to 60 hz it changes to 60 hz automatically.

**Smartphone (please complete the following information):**
 - Model Number: SM-G780G/DS
 - OS/OneUI version: android13 OneUI5.1
 - Date of latest security update, if applicable: April 1 2024
 - Stock ROM

**Comment by tribalfs** [comment]
Please provide a screen or video recording so I can look in to it. Seems you have some overlay app conflicting it. 

Also note that there's a delay added in applying the set refresh rate. Also check it also using the refresh rate monitor from the developer options

**Comment by Dimon245** [comment]
Oh, I was pretty sure it had been applying instantly before the update. Thanks for explaining, it really is delayed, apparently

**Comment by Dimon245** [comment]
Wow, you added it as a feature still? Thanks, dude!
