### ISSUE TITLE
Mi 11 U MIUI 13 

### ISSUE THREAD

**Issue by aditya10dulkar** [tribalfs/GalaxyMaxHzPub#19]
Can u make a version where in adoptive refresh rate
I can only choose 
30/60/120 
Because on mi 11 the 90hz color calibration is a mess and spoils the day experiance
So instead of 
30/60/90/120 --> 30/60/120

**Comment by Euphoria7889** [comment]
Does mi 11 support 30hz?

**Comment by aditya10dulkar** [comment]
Yes it does
By default the Always on display runs at 30 hz
But with this app it gets locked to a minimum of 60hz


P.s the 30hz only works on the Always on display , not rest of the UI

**Comment by Euphoria7889** [comment]
I see, thanks for the information.
