### ISSUE TITLE
Crash on Note 9

### ISSUE THREAD

**Issue by Princeofpersiattt** [tribalfs/GalaxyMaxHzPub#191]
The app doesn't work on my Note9. Version 8.1.28 did work perfectly but newer one (8.1.75) doesn't open at all. There is no adaptive refresh rate option on the S20. Which was present in the version 8.1.28.

**Comment by tribalfs** [comment]
Please send crashlog from your note 9.

**Comment by Princeofpersiattt** [comment]
I think it was better to have adaptive option available as regular. As it was there before, except for other features. And allowing to have trails for few more days like 3 or 4. Cause many needs more time to actually understand those features how it works. 

How can I provide bug report details and crash log?

**Comment by tribalfs** [comment]
Download and install the[ latest update](https://github.com/tribalfs/GalaxyMaxHzPub/releases/download/v8.1/galaxy_max_hz_v8.1.apk) first to see if the crash still happening.

If still happening, create complete bug report here:
https://github.com/tribalfs/GalaxyMaxHzPub/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

**Comment by Princeofpersiattt** [comment]
Thanks for increasing trail days. If each update allowed 2 days trail extra, it would've helped people know if there is something new to the update.

Version 8.1.76 is working properly now. Thanks for the update. I was facing this issue for over a week or so. Only to let you know this issue I've created account here. 

Protect battery option seems to be available in the app for Note 9. But it doesn't work. Is there a way to make this work some how? 

Isn't the options for screen off mods 'ignore when charging' should have a toggle in side those? It doesn't have toggle to enable or disable 'ignore when charging'. 

I am not sure if there is any issue with the current version. But I hope it would be as stable as the version 8.1.28.

![Screenshot_20240507-100923_Galaxy MaxHz](https://github.com/tribalfs/GalaxyMaxHzPub/assets/168981083/6ffa7b14-1464-437c-9ea7-2cd8d5a40513)
