### ISSUE TITLE
Bug: screen resolution setting doesn't update after changing. 

### ISSUE THREAD

**Issue by Xisrr1** [tribalfs/GalaxyMaxHzPub#197]
Hi, after the free version is back I can report bugs and provide feedback.

When changing the screen resolution, (in my case to 720p) it will still show the previous screen resolution as the applied option.

**Comment by tribalfs** [comment]
Please try this [build](https://github.com/tribalfs/GalaxyMaxHzPub/releases/download/v8.1/galaxy_max_hz_v8.1.apk). Thank you.

**Comment by Xisrr1** [comment]
Fixed.
