### ISSUE TITLE
Bug in seekbar behavior

### ISSUE THREAD

**Issue by ffolkes** [tribalfs/GalaxyMaxHzPub#20]
Just letting you know, there is a bug in at least one of the seekbars. When you slide down to 10Hz, the trial reminder kicks the thumb back to 24, but never actually writes the setting - meaning it stays on whatever setting it was at before. Eg. 60 -> 10 -> 24 results in min_refresh_rate still staying at 60.

**Comment by tribalfs** [comment]
Is this on S22 Ultra? I'll check. Thank you.

**Comment by ffolkes** [comment]
Yes it is.
