### ISSUE TITLE
APP IS NOT COMPATIBLE WITH 6.1UI I CANNOT INSTALL THE APK

### ISSUE THREAD

**Issue by Mewnpewn** [tribalfs/GalaxyMaxHzPub#200]
APP IS NOT COMPATIBLE WITH 6.1UI I CANNOT INSTALL THE APK

**Comment by tribalfs** [comment]
READ AND FOLLOW THE PROVIDED [INSTRUCTIONS](https://github.com/tribalfs/GalaxyMaxHzPub/releases/tag/v8.1).
