### ISSUE TITLE
Screen reverts to "Standard" (60Hz) when disconnecting from Android Auto

### ISSUE THREAD

**Issue by Ragunator** [tribalfs/GalaxyMaxHzPub#205]
Hello,

I followed the instructions to set up the app, and it works correctly in adaptive mode most of the time, however any time I connect to Android Auto, the app reverts to "Standard" (60hz) and stays at standard after I disconnect from Android Auto. To get back to adaptive, I have to reopen the app and select "Adaptive".

**To Reproduce**

A. GMH version 8.1.28, it also occured with previous versions.

B. Steps to reproduce the behavior:
1. Have GMH installed and set to "adaptive", the phone will be 120hz.
2. Start Android Auto, either wired or wireless.
3. After connecting, the phone will change to 60hz and the app will automatically change to "Standard*.
4. Disconnect from Android Auto.
5. The phone will remain at 60hz and GMH will still be set to "Standard"
6. To return to 120hz, reopen GMH and set to "Adaptive".

**Expected behavior**
The app should remain on the last selected setting after disconnecting from Android Auto.

**Smartphone (please complete the following information):**
 - Model Number: SM-S908W
 - OS/OneUI version:  OneUI 6.1, issue also occured with previous OneUI versions. 
 - Date of latest security update, if applicable: April 2024
 - Stock ROM

If you need any more details, please let me know!

**Comment by tribalfs** [comment]
Can you try with the latest version?

**Comment by Ragunator** [comment]
> Is PSM on screen off turned-on? If so, enable "Ignore while charging".
> 
> Also, can you try with the latest version?

I tried v8.1.77 and it's the same outcome.

I've been using PSM always on with the game booster method. I tried disabling PSM and using the setting in the app for PSM on screen off and it seems to work, the phone is at 120hz when I disconnect from Android Auto. The only downside is that it can only enable PSM when the screen is off, instead of 24/7.

When I have PSM enabled on the phone and PSM on screen off enabled, the phone still switches 60hz when I disconnect from Android Auto. 

Also, I haven't been able to find a setting that says "ignore while charging".

**Comment by Ragunator** [comment]
An update, I just got the paid version of the app and found that enabling the setting called "keep selected mode on PSM" seems to fix the issue. With the setting enabled, I can disconnect from Android Auto and my phone stays at 120hz. Might be something worth noting in the FAQ.

**Comment by tribalfs** [comment]
> An update, I just got the paid version of the app and found that enabling the setting called "keep selected mode on PSM" seems to fix the issue. With the setting enabled, I can disconnect from Android Auto and my phone stays at 120hz. Might be something worth noting in the FAQ. 

That's great! Thank you.
