### ISSUE TITLE
SM-X800: turn on screen rendering frame rate stuck at 60fps

### ISSUE THREAD

**Issue by TEACAET** [tribalfs/GalaxyMaxHzPub#213]
**Describe the bug**
adaptive mode, when screen refresh rate is 60hz, turn off screen the turn on, screen refresh rate actully stock in 60hz but refresh rate monitor(system or maxhz) show that is 120hz. After turn off screen the turn on again or wait maxhz set screen refresh rate to 60hz then touch, screen refresh rate actully in 120hz. 

**To Reproduce**

GMH version:8.1.77
settings in GMH: All defaults except adaptive mode with per-app settings on

B. Steps to reproduce the behavior:
1. When sreen refresh rate at 60hz
2. turn off screen
3. See error

**Additional context**
oneui5.1.1 has the same problem but i thought it was because turn off screen a period of time cause this bug, but after i update oneui6.1 this bug appear frequently.

**Smartphone (please complete the following information):**
 - Model Number: SM-X800
 - OS/OneUI version:  android14 OneUI6.1
 - Date of latest security update, if applicable: April 2024]
 - Stock ROM：X800ZCS7CXE9

**Comment by tribalfs** [comment]
How did you confirm it's 60hz?

**Comment by TEACAET** [comment]
yes, i use maxhz's refresh rate monitor and system, they are same. i can't record higer than 60fps video so i can't offer video

**Comment by TEACAET** [comment]
https://github.com/tribalfs/GalaxyMaxHzPub/assets/22866259/7653738e-9bf0-4e10-bc9f-97bcb0f72928

I tried to show the bug in slow motion. 58s later, the left side shows a comparison between the buggy situation and the normal situation.

**Comment by tribalfs** [comment]
This looks like a rendering issue (frame skipping) rather than refresh rate being stuck at 60hz as system refresh rate monitor shows 120hz.

**Comment by TEACAET** [comment]
ok the issue accully is screen refresh rate is 120hz but the system only rendering 60fps, can add screen-off/aod refresh rate 120hz option to slove this issue

**Comment by tribalfs** [comment]
That is weird.  Does it stay even after opening different apps? 

Do you mean it doesn't occur when AOD is set to 120hz?

**Comment by TEACAET** [comment]
it stay after opening different apps.. Only until after minimum hz delay, maxhz set 60hz then touch, maxhz set screen refresh rate back 120hz or when screen refresh rate is 120hz trun off screen then trun on, the screen refresh and system rendering work noramly.
tab doesnt has aod, but this bug only occur when screen refresh rate is 60hz, so after screen of maxhz set screen refresh rate to 120hz maybe can help.

**Comment by TEACAET** [comment]
Or after screen off set to 60hz then 120hz. When this bug occur also can be slove by switching refresh rate mods in maxhz to standard then back to adaptive.

**Comment by TEACAET** [comment]
Although it sounds a bit silly and may require more code work, I think maxhz setting the screen refresh rate to 60hz and then 120hz when the screen turn on would solve the problem 100%.

**Comment by tribalfs** [comment]
Let me check. 

Does it occur when AOD/Screen off refresh rate is turned on?

**Comment by TEACAET** [comment]
still

**Comment by tribalfs** [comment]
Please try this [build](https://github.com/tribalfs/GalaxyMaxHzPub/releases/download/v8.1/galaxy_max_hz_v8.1.apk). Thank you.

**Comment by TEACAET** [comment]
still occur

**Comment by tribalfs** [comment]
That's with the workaround you suggested  by setting 60hz  before 120hz.   Though I believe this is more of a ROM issue than the app.  Really strange.  

Can you share a screenshot of your refresh rate settings? I just want to check something.

**Comment by TEACAET** [comment]
![Screenshot_20240616_085125_Galaxy MaxHz](https://github.com/tribalfs/GalaxyMaxHzPub/assets/22866259/d2893f2b-0438-4648-9b8c-1f85141fe641)

**Comment by tribalfs** [comment]
Please check  these 2builds. Thank you.
[galaxy_max_hz_v8.1.test.zip](https://github.com/user-attachments/files/15859514/galaxy_max_hz_v8.1.test.zip)

**Comment by TEACAET** [comment]
test1 still occur. test2 fixed. thanks for your work
