### ISSUE TITLE
Fixes in adaptive mode

### ISSUE THREAD

**Issue by Y4d13l** [tribalfs/GalaxyMaxHzPub#214]
Hello dear developers of the GMHz app. I am very happy with how much the application has improved with the passage of time and the dedicated effort of its development team. Today I want to share an error that I notice in the adaptive mode, and that is that the adaptive mode is supposed to change to 60 Hz while the screen is not interacting with the user after 1.5 seconds, and if it detects movement it changes to 120 Hz; However, I notice how there are fluctuations when there is no interaction with the screen, it changes from 60 to 120, I repeat without interaction with the screen. I have noticed that with notifications or mobile data traffic itself it is enough for the adaptive mode not to respect 60Hz when we are not interacting with the touch panel. Please I would like you to correct this in future updates. Greetings and congratulations for your work.

https://github.com/tribalfs/GalaxyMaxHzPub/assets/162078059/8e394878-f64b-49e2-8baa-86575eb8609c

**Comment by tribalfs** [comment]
This is an expected behavior. Not only interactions but also screen updates trigger refresh rate update. This is necessary  to improve smoothness. This is also similar to how samsung's native adaptive works.
