### ISSUE TITLE
Phone reboots

### ISSUE THREAD

**Issue by Leninpisel** [tribalfs/GalaxyMaxHzPub#22]
After enabling the app, setting the max phone refresh rate to 96 and the minimum to 10 my phone rebooted and it happened any time i restarted the app.
I have an Exynos s22 ultra on the latest firmware.

**Comment by tribalfs** [comment]
That's strange. Do you have a modified rom?

**Comment by Leninpisel** [comment]
> That's strange. Do you have a modified rom? The app is tested on the same device and doesn't have this issue.

I suppose that the problem was related to the app since it started only after i used that, i don't know if it's due to the app itself or conflicts with other things.

**Comment by Leninpisel** [comment]
I remembered that the problem started only after enabling usb debugging, i don't know if it was a coincidence tho.

**Comment by tribalfs** [comment]
Using custom rom?

**Comment by Leninpisel** [comment]
No, just official firmware, latest update.
I just don't know if it was apps fault or something else, but I had this problem only after enabling the app.
I'm using it again and rn I'm not having any issue.
