### ISSUE TITLE
Strange issue with trial and updating

### ISSUE THREAD

**Issue by drbeat** [tribalfs/GalaxyMaxHzPub#23]
So today I had a really strange Issue with the app and I had to buy premium to prevent it.
I was on the 7-days free trial with energy saving on but Hz set to adaptiv and preventing it to go to High.

I checked for update and there was one with 40_3 and it updated successfully but then the trial was gone and my phone got really slow.
The phone seemed like to switch from adaptiv to high and back all the time.

The only way I could stop that was through buying premium to activate the extra features. Then it stopped this behaviour.

I am really happy buying premium but this was really strange.

Also I am using the app on a german phone and the translation is somehow dodgy. On some places its really bad but its fine most of the time. I would like to set it to english without setting my phone to english, if that is possible?

**Comment by tribalfs** [comment]
That's strange indeed. Will look into it.  Seems related to prevent high settings. Thanks for this info and for the purchase.
Re independent language switcher,  it is not implemented on GMH.
The faster way would be fixing those problematic German strings.  Can you help me? 
Thank you.

**Comment by tribalfs** [comment]
-Bug related to "Prevent Switching to High" fixed in v7.14.50
