### ISSUE TITLE
Tiktok keeps the screen at 120hz on mi 11.

### ISSUE THREAD

**Issue by Euphoria7889** [tribalfs/GalaxyMaxHzPub#25]
In tiktok screen stuck at 120hz when playing videos, only time it goes 60 is when you pause the video. Xiaomi mi 11. Also in the ui there's a bug that switches RR rapidly between 120 and 60, most noticeable when first opening an app or on the recents, and accessing apps from recents.

**Comment by Euphoria7889** [comment]
Tiktok still runs at the highest refresh rate even when playing videos. On
7.14.51 it works fine, in 7.14.52 it has this bug, i think the issue is in
the accessibility because when disabled in settings it works correctly.

**Comment by tribalfs** [comment]
I think I found the reason - you are using  the non-google-playstore version of tiktok.
[Download](https://github.com/tribalfs/GalaxyMaxHzPub/releases/download/v7.14/galaxy_max_hz_v7.14.53.apk) and install this build.

**Comment by Euphoria7889** [comment]
Thank you very much, i'll try the playstore version, if still does not work
i',ll install this one.

**Comment by Euphoria7889** [comment]
Here are screenshots of in-app settings.
