### ISSUE TITLE
Flashing and screen color change at low light level

### ISSUE THREAD

**Issue by duonghaitlc** [tribalfs/GalaxyMaxHzPub#26]
1. Use phone at night
2. Screen brightness is low
3. Using some apps with black background
4. Notice flashing color is changed sometimes

**Comment by tribalfs** [comment]
This issue is on GMH.
Please read item 10 in [FAQs](https://forum.xda-developers.com/t/app-galaxy-max-hz-refresh-rate-mods-screen-off-mods-qs-tiles-tasker-support-and-more.4181447/post-83785135)
