### ISSUE TITLE
Constant switching between 120 and 60hz when watching content

### ISSUE THREAD

**Issue by PapaBear55** [tribalfs/GalaxyMaxHzPub#30]
Whenever I'm watching a Twitch stream or an Instagram storie/reel the refresh rate never stays at 60hz. It constantly jumps between 60 and 120.
Device is S20+

**Comment by PapaBear55** [comment]
I also notice a slight microstuttering when switching between 60 to 120hz when the screen brightness is above ≈50%

**Comment by tribalfs** [comment]
There maybe some contents/views that's moving that you might not noticed while watching  - that triggers it.
But let us look closer. Can  you attached a link of the screen recording here? Thank you.

**Comment by PapaBear55** [comment]
Oh yeah that's probably what causes it. Here is an example of such behavior in the Twitch app

https://user-images.githubusercontent.com/79588468/175767437-3d89516b-52b4-4336-8fd1-fb1eaa0e5026.mp4
