### ISSUE TITLE
Adaptative refresh rate not working on Samsung Note (and only this)

### ISSUE THREAD

**Issue by yanishoss** [tribalfs/GalaxyMaxHzPub#33]
**Device**: Samsung Galaxy Tab S8 Ultra

On Galaxy Mod Hz Premium, Adaptative Refresh Rate works fine on every app except Samsung Notes (which is problematic since it can save a lot of battery if it could switch to 60hz when watching documents

Thanks a lot!

**Comment by tribalfs** [comment]
That's intended to preserve smoothness while writing and using SPEN. 
Samsung notes app uses a surface that GMH is unable to detect when you are writing on it.
