### ISSUE TITLE
refresh rate drops to 10hz on every app that uses the camera except the stock camera app

### ISSUE THREAD

**Issue by Alvyssy** [tribalfs/GalaxyMaxHzPub#36]
Title, every app drops to 10hz when using the camera even if the minimum is set to 120hz, except for the stock camera app. I'm forced to put the refresh rate to standard mode to use them. I'm using the S22 with the last version of the app

**Comment by tribalfs** [comment]
Thanks. Will look into it.

**Comment by tribalfs** [comment]
Hi! We are unable to replicate this issue. 
Can you send us a screen recording of the issue? Pls also provide the details asked [here](https://github.com/tribalfs/GalaxyMaxHzPub/blob/main/.github/ISSUE_TEMPLATE/bug_report.md).
Thank you.

**Comment by caingatcarl** [comment]
Screen recording doesnt show that it drops to 10hz but a screenshot does

![Screenshot_20220804-153445_Galaxy Max Hz](https://user-images.githubusercontent.com/110513078/182791211-c77e1333-98ba-4b2a-930b-c0f27f93ee61.jpg)
![Screenshot_20220804-153546_Messenger](https://user-images.githubusercontent.com/110513078/182791294-8489de9e-e2e1-442c-992f-cc0d3fef86fb.jpg)
.

**Comment by tribalfs** [comment]
Screen recording should not affect it.

**Comment by tribalfs** [comment]
You can try recording it with other phone.

If you're interested to try v8-alpha:
https://github.com/tribalfs/GalaxyMaxHzPub/releases/tag/v8.0.0

**Comment by caingatcarl** [comment]
> Screen recording should not affect it.

Already tried it but it restricts the refresh rate to 60hz while screen recording. Therefore I can't show the real issue using that. Ill try tomorrow to record it using other phone. I dont have a spare right now

**Comment by caingatcarl** [comment]
> You can try recording it with other phone.
> 
> If you're interested to try v8-alpha: https://github.com/tribalfs/GalaxyMaxHzPub/releases/tag/v8.0.0

Thank you sir.

**Comment by caingatcarl** [comment]
Issue is still there. Also i can't activate my premium feature
![Screenshot_20220804-202815_Messenger](https://user-images.githubusercontent.com/110513078/182847738-d0fb702e-e71d-4fef-bbdb-1ddf8176b3c4.jpg)
![Screenshot_20220804-203001_Galaxy MaxHz](https://user-images.githubusercontent.com/110513078/182847762-4fcac00b-5b16-4f56-9634-2ef704f1367b.jpg)

**Comment by caingatcarl** [comment]
There is also a bug in "show refresh rate" on status bar
https://user-images.githubusercontent.com/110513078/182848326-14f77b2d-f87c-4f51-8e7d-f5e117e7de55.mp4

**Comment by caingatcarl** [comment]
"Show refresh rate" bug keep showing tho it is disabled

https://user-images.githubusercontent.com/110513078/182849778-ccf5ca60-c206-4c1c-8dce-fab496b67350.mp4

**Comment by tribalfs** [comment]
Clear app data after installing this alpha update.

**Comment by caingatcarl** [comment]
> Clear app data after installing this alpha update.

Why cant i activate it? I do have mobile data turned on
![Uploading Screenshot_20220804-210351_Galaxy MaxHz.jpg…]()

**Comment by tribalfs** [comment]
Try to clean install if issue persist.

**Comment by caingatcarl** [comment]
Already tried everything. Restart my phone. Uninstall previous app. Reinstall the app. Connected via hotspot to activate premium. reinstall the v7.14.58 and tried to activate the activation code. Still i cant activate it. Always popping the error message that i cant connect to the internet

**Comment by tribalfs** [comment]
Seems like our backend provider went down for a while. 
I check now it's already online.

**Comment by Alvyssy** [comment]
The issue was gone with version 7 now I have installed version 8 and the issue reappeared, I cleaned all data from v7 before installing v8, I guess I will have to uninstall until the issue is gone.
