### ISSUE TITLE
Min refresh rate

### ISSUE THREAD

**Issue by duonghaitlc** [tribalfs/GalaxyMaxHzPub#37]
1. Play native youtube app
2. In note 20 ultra video play in lowest refresh rate 48hz.
3.is this possible to set other apps play videos under 48hz mode. Currently it's 60hz

**Comment by tribalfs** [comment]
Please check https://forum.xda-developers.com/t/app-galaxy-max-hz-refresh-rate-mods-screen-off-mods-qs-tiles-tasker-support-and-more.4181447/post-87206713
