### ISSUE TITLE
v8.0.0 alpha 1

### ISSUE THREAD

**Issue by drbeat** [tribalfs/GalaxyMaxHzPub#38]
Cannot set Max/Min Hz
Not sure but basics not working
![Screenshot_20220727-205332_Galaxy MaxHz](https://user-images.githubusercontent.com/436470/181350446-81d52048-c8d9-4e44-ad7a-83eb4f33b6c2.jpg)

Also not all Strings are on POEditor.com

**Comment by tribalfs** [comment]
The profile is not properly loaded. Can you try reload profile in the menu while connected to net?

**Comment by drbeat** [comment]
Cleated app data and tried again. Still not working.
Also I reinstalled and It did also not work.

**Comment by tribalfs** [comment]
We corrected something on our backend. Just try reloading profile while connected to internet. Thank you.

**Comment by drbeat** [comment]
Works now!

tribalfs ***@***.***> schrieb am Mi., 27. Juli 2022, 22:04:
