### ISSUE TITLE
Pre app settings, Doesn't reach 10hz, if default refresh rate 120 to 24 hz

### ISSUE THREAD

**Issue by Elzeiny-S22U** [tribalfs/GalaxyMaxHzPub#40]
**Important: Before submitting a bug, ensure to check [FAQs](https://github.com/tribalfs/GalaxyMaxHzPub/wiki/FREQUENTLY-ASK-QUESTIONS-(FAQs))  and in the app description in the appropriate XDA forum thread for your device to ensure that the behavior is not expected or not part of the limitation of the app.**

**Describe the bug**

**To Reproduce**

A. GMH version and the exact settings in GMH

B. Steps to reproduce the behavior:

**Expected behavior**

**Screenshots**
If applicable, please include screenshots and/or [screen recording](https://play.google.com/store/apps/details?id=us.rec.screen) to help explain your problem. 

**Smartphone (please complete the following information):**
 - Model Number: [e.g. SM-S908B]
 - OS/OneUI version:  [e.g. android12 OneUI4.1]
 - Date of latest security update, if applicable: [e.g. June 2022]

**Additional context**

**Crashlog**
If GMH crashes on your device, please include the crashlog of your device.  Just execute the following adb command.  Do this right after the crash (device must not be rebooted yet):
`adb logcat -b crash > crashlog.txt`
_Ctrl+C_ after 10seconds.
Then locate _crashlog.txt_ file in your adb installation folder then send it to tribalfs@gmail.com.

**Comment by Elzeiny-S22U** [comment]
Pre app settings, Doesn't reach 10hz, if default refresh rate 120 to 24 hz

**Comment by tribalfs** [comment]
Hi! Can you share a screen recording? Thanks.

**Comment by Elzeiny-S22U** [comment]
https://user-images.githubusercontent.com/110348453/182038541-fa4a8ec7-360b-4f16-b72f-d00bd1ce69ec.mp4

**Comment by tribalfs** [comment]
Thank you. Is that happening to every app or only on Telegram?

**Comment by Elzeiny-S22U** [comment]
It's on every app that I wanted to reduce its refresh rate till 10hz, while the overall refresh rate are minimum of 24hz only ..

**Comment by tribalfs** [comment]
Thanks. Will look into it.

**Comment by tribalfs** [comment]
By the way, what's the exact model of your device? Thank you.

**Comment by Elzeiny-S22U** [comment]
> By the way, what's the exact model number of your device? Thank you.

S22 Ultra
Model number S908E
Snapdragon Processor

**Comment by Elzeiny-S22U** [comment]
> Did you set brightness threshold to higher number?

When 120 t0 10hz
I leave brightness threshold on the lowest value as it is as soon as when you trigger 10hz in default refresh rate

**Comment by tribalfs** [comment]
Pls check v8.0.0_alpha7 update.
