### ISSUE TITLE
After Unlocking Device Smoothness Reverts Back 60 Hz While Screen-off Power Saving Mode

### ISSUE THREAD

**Issue by Osmanakar312** [tribalfs/GalaxyMaxHzPub#41]
I am using 8.0.0-alpha6 version. Screen-off PSM enabled on Galaxy Max Hz app. While locking device everything is fine, but after unlocking device device sets smoothness to 60 Hz and won't increase 120 Hz back. You have to manually increase in built-in selector or via app. I am using Samsung Galaxy S20+ with One UI 4.1.

**Comment by tribalfs** [comment]
Using high mode?

**Comment by Osmanakar312** [comment]
I am using high mode, not adaptive. Now i realised caused by "Force lowest Hz" setting. While this setting turned on, this problem appears. I throught caused by screen-off PSM mode before.

**Comment by tribalfs** [comment]
Confirming this bug. Will fix it in the next alpha update. Thank you.

**Comment by tribalfs** [comment]
Pls check v8.0.0_alpha7 update.
