### ISSUE TITLE
Backup Pre-App settings or Overall App

### ISSUE THREAD

**Issue by Elzeiny-S22U** [tribalfs/GalaxyMaxHzPub#43]
**Important: Before submitting a bug, ensure to check [FAQs](https://github.com/tribalfs/GalaxyMaxHzPub/wiki/FREQUENTLY-ASK-QUESTIONS-(FAQs))  and in the app description in the appropriate XDA forum thread for your device to ensure that the behavior is not expected or not part of the limitation of the app.**

**Describe the bug**

**To Reproduce**

A. GMH version and the exact settings in GMH

B. Steps to reproduce the behavior:

**Expected behavior**

**Screenshots**
If applicable, please include screenshots and/or [screen recording](https://play.google.com/store/apps/details?id=us.rec.screen) to help explain your problem. 

**Smartphone (please complete the following information):**
 - Model Number: [e.g. SM-S908B]
 - OS/OneUI version:  [e.g. android12 OneUI4.1]
 - Date of latest security update, if applicable: [e.g. June 2022]

**Additional context**

**Crashlog**
If GMH crashes on your device, please include the crashlog of your device.  Just execute the following adb command.  Do this right after the crash (device must not be rebooted yet):
`adb logcat -b crash > crashlog.txt`
_Ctrl+C_ after 10seconds.
Then locate _crashlog.txt_ file in your adb installation folder then send it to tribalfs@gmail.com.

I've been using the Galaxy Max Hz App since early May 2022 when I Purchased S22 Ultra,, I recommend Many friends to buy the Premium features of the App, i usually clear Data & cash of the App after every updates, now after Adding the revolutionary option to Pre-app setting of fixed or adaptive custom refresh rate,, I really hope you Add an option to somehow Backup Pre-App settings or even the whole Galaxy Max Hz app Backup to easily restore after clearing Data & cashe after every updates to ensure App functionality and fluidity
At the same time it'd be time and effort saving specially after customizing Many apps Pre-App settings refresh rate

**Comment by tribalfs** [comment]
Ho!
Will add soon. Will work on it.
Will close this as this not an issue but a feature request.
