### ISSUE TITLE
App's UI suggestion

### ISSUE THREAD

**Issue by BlackMesa123** [tribalfs/GalaxyMaxHzPub#44]
I want to suggest you to move using our [oneui-core](https://github.com/OneUIProject/oneui-core) (and optionally our [oneui-design](https://github.com/OneUIProject/oneui-design)) libraries to work with the app's UI, you can download [here](https://github.com/OneUIProject/oneui-design/raw/main/sample-app/release/sample-app-release.apk) the lib's sample app to see how the lib looks and works.

**Comment by tribalfs** [comment]
Thanks. Let us check.
