### ISSUE TITLE
Per-app settings not working on fixed 120hz

### ISSUE THREAD

**Issue by SilverQi** [tribalfs/GalaxyMaxHzPub#45]
Model: Sm-S908U1
Reproduce: 
![Screenshot_20220825-160109_Galaxy MaxHz](https://user-images.githubusercontent.com/112133421/186783396-cb8507bb-b7c7-4814-a5d0-73fa0e43e1cc.jpg)
When using adaptive option and setting app refresh rate to 120hz, app will run in 60hz unless high option is selected.

**Comment by tribalfs** [comment]
We can't reproduce with the details provided.
Please provide required details including a screen recording.
