### ISSUE TITLE
Per-App Fixed Refresh Rate Not Working 

### ISSUE THREAD

**Issue by SilverQi** [tribalfs/GalaxyMaxHzPub#46]
S22 ultra sm_908u1

Reproduce: 
https://user-images.githubusercontent.com/112133421/186941479-74eac096-b4b2-49d7-9719-3d2aec06f0dd.mp4

Expected outcome: "Adaptive" option and setting fixed Refresh Rate in per app settings does not work. Only by using setting "high" is the app able to be at 120hz.

**Comment by tribalfs** [comment]
It's not a bug. It's  the app that requested 60hz in adaptive mode (fixed
is not same as high mode). Fixed option in Per app  is under Adaptive mode.

**Comment by tribalfs** [comment]
120Hz in high mode is not useful if the game set itself to render frames for 60hz display. That's why display only provides 60hz while in fixed mode.
