### ISSUE TITLE
Ask for activation code

### ISSUE THREAD

**Issue by ataman76** [tribalfs/GalaxyMaxHzPub#49]
**Important: Before submitting a bug, ensure to check [FAQs](https://github.com/tribalfs/GalaxyMaxHzPub/wiki/FREQUENTLY-ASK-QUESTIONS-(FAQs))  and in the app description in the appropriate XDA forum thread for your device to ensure that the behavior is not expected or not part of the limitation of the app.**

**Describe the bug**

**To Reproduce**

A. GMH version and the exact settings in GMH

B. Steps to reproduce the behavior:

**Expected behavior**

**Screenshots**
If applicable, please include screenshots and/or [screen recording](https://play.google.com/store/apps/details?id=us.rec.screen) to help explain your problem. 

**Smartphone (please complete the following information):**
 - Model Number: [e.g. SM-S908B]
 - OS/OneUI version:  [e.g. android12 OneUI4.1]
 - Date of latest security update, if applicable: [e.g. June 2022]

**Additional context**

**Crashlog**
If GMH crashes on your device, please include the crashlog of your device.  Just execute the following adb command.  Do this right after the crash (device must not be rebooted yet):
`adb logcat -b crash > crashlog.txt`
_Ctrl+C_ after 10seconds.
Then locate _crashlog.txt_ file in your adb installation folder then send it to tribalfs@gmail.com.

**Comment by ataman76** [comment]
Please send me the activation code (to the e-mail below) for the Premium version again, because I lost it. My paypal address from which I made the payment is: tomaszpf@wp.pl

Regards

**Comment by tribalfs** [comment]
Resent. Pls check your email.
