### ISSUE TITLE
Max hz button

### ISSUE THREAD

**Issue by Farinha114** [tribalfs/GalaxyMaxHzPub#50]
I always used this button to quickly change between 60 and 120 adaptive, but in 8.0 it doesn't exist anymore

**Comment by tribalfs** [comment]
Just use the min max hz shortcut

**Comment by Farinha114** [comment]
If you mean this button, it takes me to this page, which a can't change the max or minimum hz, and in the anterior version, only clicking the button it would change without opening the app
![Screenshot_20220920_115320](https://user-images.githubusercontent.com/113990040/191346436-982dc869-4b8f-4806-b26a-0a55a20511ed.jpg)
![Screenshot_20220920-115456_Galaxy MaxHz](https://user-images.githubusercontent.com/113990040/191346441-f0bd9a8f-342b-4141-a97e-99910b9e5276.jpg)

**Comment by tribalfs** [comment]
You can long press it to quickly open the app and set to standard mode 60hz.

**Comment by Farinha114** [comment]
So it can be a tip, on the next release add the option to change
immediately, thanks for your response.

Em ter., 20 de set. de 2022 22:08, tribalfs ***@***.***>
escreveu:

> You can long press it to quickly open the app and set to standard mode
> 60hz.
>

**Comment by Farinha114** [comment]
If you mean this button, it takes me to this page, which a can't change the
max or minimum hz, and in the anterior version, only clicking the button it
would change without opening the app

Em ter., 20 de set. de 2022 09:32, tribalfs ***@***.***>
escreveu:

**Comment by tribalfs** [comment]
Please install this [build](https://github.com/tribalfs/GalaxyMaxHzPub/releases/download/v8.0.0/galaxy_max_hz_v8.0.0.apk). The slider will now allow to select 60Hz both as min and max Hz.
