### ISSUE TITLE
S-Pen hovering and 10hz mode not bumping RR back to 120

### ISSUE THREAD

**Issue by arunkcx** [tribalfs/GalaxyMaxHzPub#52]
**Describe the bug**

When using the S-Pen on an S22 Ultra / S21 Ultra / Fold 3 / Fold 4, and if the refresh range is set to 10-120 Hz, the screen can go down to 10 Hz and stay at 10 Hz even if the pen is hovering over the screen and the cursor responds/hovers at 10 Hz. As soon as the screen is tapped with the pen, the refresh jumps back up. 
When using 24 Hz as the minimum, this is not an issue, the screen goes back up from 24 to 120 when the Pen is hovering.

**To Reproduce**

A. GMH version and the exact settings in GMH

GMH 8.0.0 Stable with Premium on SM-F936, can confirm also occurs on SM-S908
Refresh Rate mode - Adaptive
Default Refresh Rates
NMP 10 - 120 Hz
PSM 10 - 120 Hz
Brightness Threshold 0

B. Steps to reproduce the behavior:

1. Use any of the S Pen supported devices, set refresh range from 10-120 Hz
2. Hover the pen on the screen but do not touch the screen.
3. Issue Does Not occur if Minimum set to 24 Hz, only occurs when minimum set to 10 Hz

**Expected behavior**

The Refresh rate should jump back up to the Max Hz when touching the screen with the Pen, this works absolutely fine if the minimum refresh rate is set to 24hz, but when set to 10hz, it cannot jump back up or respond to the pen when hovering.
 
**Smartphone (please complete the following information):**

 - Model Number: SM-F936, SM-F926, SM-S908, SM-S998
 - OS/OneUI version:  Android12 OneUI4.1.1, seen also on 4.1
 - Date of latest security update, if applicable: September 2022, seen on older versions as well

**Additional context**
N/A

**Crashlog**
No Crashes

**Comment by tribalfs** [comment]
Hi! Thank you for the report. However this is already a known limitation of the app as stated in[FAQ #7](https://github.com/tribalfs/GalaxyMaxHzPub/wiki/Frequently-Asked-Questions-(FAQs)#7-how-does-gmh-adaptive-mod-work). The only way to address this is to set min hz to 24hz for these apps. Thank you
