### ISSUE TITLE
S20 stays Standard mode after screen wakeup when bixby routine switched PSM off and on while screen off

### ISSUE THREAD

**Issue by red9350** [tribalfs/GalaxyMaxHzPub#53]
I have a Bixby Routine that puts the phone in Power Saving mode when it's charging. Galaxy Max Hz doesn't interact well with it, as it'll go into Normal mode and stay in Normal mode, instead of going back to Adaptive.

**To Reproduce**

A. GMH 8.0.0.3, Adaptive, prevent switch to High, Force lowest, PSM on screen-off, Quick Doze.

B. Steps to reproduce the behavior:
1. Create a Bixby Routine that, when the phone is charging, puts the phone into Power Saving Mode
2. Set GMH as per point **A.**
3. Turn off the display
4. Connect charging cable with display off
5. Disconnect charging cable with display off
6. Turn on the display and check GMH: it'll be in Normal mode and it'll have to be manually put back into Adaptive

**Expected behavior**
GMH should go back to Adaptive once the Power Saving Mode is disabled (automatically by Bixby Routine in this case, when the charging cable is disconnected). Please note this only happens when the screen is off, if you follow the same steps with the screen on, GMH behaves correctly and goes back to Adaptive.

**Smartphone:**
 - Model Number: SM-G980F (Exynos S20)
 - OS/OneUI version:  Android 12, OneUI4.1
 - Date of latest security update: August 2022

**Comment by tribalfs** [comment]
Hi!

Thanks for the report.

However, please note that, except if triggered by GMH itself, GMH does not intervene with system's response on turning off power saving mode - what ever the system's behavior is kept as is. 

Suggestion: Try to add "Motion smoothness > High" in your routine's action after turn off PSM.  If "prevent switch to High" is turned on, GMH can react to it and switch motion smoothness to Adaptive.

**Comment by red9350** [comment]
Thanks for the workaround! Unfortunately, it still doesn't work as expected and stays in Normal mode after the cable is disconnected. This only happens when GMH is active (happens both in Adaptive and in High mode!). When GMH is uninstalled, the phone correctly goes back to 120Hz when the cable is disconnected

**Comment by tribalfs** [comment]
Seems a conflict with Force Lowest S20.
Try to disable Force Lowest Hz and see if it works.

**Comment by red9350** [comment]
Yep that's it! With Force Lowest disabled, the problem does not occur
