### ISSUE TITLE
Activation code issue

### ISSUE THREAD

**Issue by Lapingaman** [tribalfs/GalaxyMaxHzPub#54]
Hi, I donated but did not get an email with the activation code. I paid via PayPal. Please respond. Thanks.

**Comment by tribalfs** [comment]
Please email us details @ tribalfs@gmail.com

**Comment by Lapingaman** [comment]
Ok I will. Thanks

**Comment by tribalfs** [comment]
Please email your paypal email address to ***@***.***

Thank you.

**Comment by tribalfs** [comment]
It seems you paid using the wrong chanel, NOT using the buy button on the
app.

Please email your paypal email address to ***@***.***

Thank you.

**Comment by tribalfs** [comment]
tribalfs@gmail.com

**Comment by Lapingaman** [comment]
***@***.***

**Comment by Lapingaman** [comment]
zeopulos
