### ISSUE TITLE
Current mode switches to Standard when the USB-C port is plugged and unplugged while screen is off  on Poco F4 GT

### ISSUE THREAD

**Issue by pauloup** [tribalfs/GalaxyMaxHzPub#58]
Hi! I started having this issue a few days ago, where the current mode switches to "Standard" by itself, so the screen stays fixed at 120Hz, and I had to manually change it back to Adaptive to get 60/120Hz.

I was able to reproduce the issue:
https://photos.app.goo.gl/1MgFKGqUqL9MTJfM9

In the video, I've made these 4 tests: 
1. I switch from Standard to Adaptive, leave the app and come back: Adaptive stays selected.
2. I lock and turn the screen off and on again: Adaptive stays selected.
3. I plug in a USB-C to P2 audio dongle, leave the app and come back, and then turn the screen off and on: Adaptive stays selected.
4. Finally, what triggers the issue: I turn the screen off, plug the USB-C to P2 audio dongle, and turn the screen on: Standard is now selected.

I can reproduce this consistently, and it also happens if I plug the charging cable when the screen is off, instead of the dongle.

So I think it's something related to the USB-C port is plugged or unplugged when the screen is off.

I don't use any other GMH option besides Adaptive mode and Per-app settings, so no Screen-off mods.

I know my device Poco F4 GT (Xiaomi/MIUI) is not officially supported, but I thought it could be useful to share these tests and my thoughts to help others with Samsung devices and similar issues, like #53.

Thank you for working on this amazing app!

**Comment by pauloup** [comment]
Workaround: Enabling "Keep smoothness on PSM" seems to fix the issue.

**Comment by tribalfs** [comment]
Not sure how MIUI operates on this, but it seems power saving mode is being triggered when usb is unplugged (since you didn't enable any screen off mods). Unfortunately, we can't test it ourselves since I don't have the device.

**Comment by tribalfs** [comment]
Issue #53 is a different issue - conflict with force lowest hz screen of mod - unique to S20 due to it's peculiar refresh rate profile.
