### ISSUE TITLE
Request to add refresh rate toggle per app

### ISSUE THREAD

**Issue by Denyah1707** [tribalfs/GalaxyMaxHzPub#6]
Hey:
For most apps for me, running at a 48hz at a minimum is fine. However for applications such as twitch and twitter, when I leave the screen to idle for long enough, it goes down to 48hz and stops a smooth watching experience. Is it possible in future to have a per app minimum refresh rate toggle? That would be awesome. Thank you!

**Comment by Zeioth** [comment]
This would be cool for games and stuff.
