### ISSUE TITLE
screen color

### ISSUE THREAD

**Issue by hointat123** [tribalfs/GalaxyMaxHzPub#62]
When I use Adaptive mode, when the HZ changes, the screen color becomes greenish, and the color jumps back and forth between blue and green.

Model Number: [SM-G9980]
OS/OneUI version: [Android12 OneUI4.1]
Date of latest security update, if applicable: [September 1, 2022]
Stock[

https://user-images.githubusercontent.com/97159295/195958847-9be52c57-4a36-4633-8970-e795c5ef8ab5.mp4

](url)

**Comment by tribalfs** [comment]
Pls read FAQs.
