### ISSUE TITLE
Pre App settings doesn't apply, android 13, one Ui 5, beta 4

### ISSUE THREAD

**Issue by Elzeiny-S22U** [tribalfs/GalaxyMaxHzPub#64]
Hi there
I'm using the latest version of the Galaxy Max Hz, just released 6hrs from now 
I'm Premium Activated Properly
The app was clean new installation not an updated one
I'm running **Android 13, One Ui 5, beta 4 build** S22 Ultra 
The pre app settings just doesn't seem to Apply properly at all Apps.
I'm limiting Facebook app to 96hz to 24hz, Actually it runs at 60hz to 24hz, not as it should..
Hope you manage to Address such issue ...

**Comment by tribalfs** [comment]
Possibly you set a very low screen brightness.
