### ISSUE TITLE
Force Hz on Power Saving Mode is not working after update to OneUI 5.0

### ISSUE THREAD

**Issue by tinspham209** [tribalfs/GalaxyMaxHzPub#68]
After upgrade to OneUI 5.0 on my Samsung Galaxy S21 Ultra. Current setting of Refresh Rate on PSM is not working
My setting: PSM: 48-120Hz
But the app is only can 48-60Hz.

MaxHz version: 8.0.0.10.

You can see the screenshot, Refresh rate monitor on status bar is 60Hz

![Screenshot_20221111_092743_Galaxy MaxHz](https://user-images.githubusercontent.com/34814999/201249835-851ebf5d-7776-4a8e-b382-3b39050a7215.jpg)

**Comment by tribalfs** [comment]
Unfortunately, OneUI5 already patched the bug that allows the app to automatically bypass the 60Hz limit on power savings mode.  You can try the extra steps that is indicated in the app.
