### ISSUE TITLE
App glitches google chrome when used.

### ISSUE THREAD

**Issue by Theguysayhi** [tribalfs/GalaxyMaxHzPub#7]
![Screenshot_20211121-211541_Chrome](https://user-images.githubusercontent.com/22719296/142780455-b589e376-f224-4f37-a009-f60276f44954.jpg)

Great app, but it glitches my chrome app so I can't see tab previews as shown.
I'm using my Galaxy fold 3.

I know the app causes this as when I uninstall/turn it off under settings>accessibility, the problem resolves. Will there be a fix for this?

**Comment by tribalfs** [comment]
I was able to find a way to avoid and remove accessibility component that disables chrome's swipe to switch tab and the same time retaining GMH functionalities. Will be coming on v7.14.20
