### ISSUE TITLE
96 Hz mode note working 

### ISSUE THREAD

**Issue by Leninpisel** [tribalfs/GalaxyMaxHzPub#70]
Phone: S22 ultra (Exynos)
96 Hz mode not working properly, i set it in the app with the adaptive mode, but it doesn't work (or it works for a while but after putting phone in standby and turning it on again it drops to 60 Hz)
Power saving mode was obviously off.
![Screenshot_20221120_222323_Galaxy MaxHz](https://user-images.githubusercontent.com/99171834/202926921-dbd5a6b4-5d77-49d2-be56-bb10166febac.png)
(Screenshot taken after touching the display in order to enable the highest refresh rate)

**Comment by tribalfs** [comment]
Please read app info. It's because of the  higher brightness threshold for 96hz that was set by Samsung on your device. That's beyond control of GMH. You can set brightness a little higher to keep 96hz.
