### ISSUE TITLE
Protect battery mod doesn't work when charghing wireless

### ISSUE THREAD

**Issue by StefanoMarchesi** [tribalfs/GalaxyMaxHzPub#71]
**Describe the bug**
Protect battery mod doesn't work when charghing wireless.
When charging with cable it works and limitis the charge to what is set in the app and even shows a message on the always on display, when charging wireless it is completly ignored, no message on the always on display and the charge goes up to 100%.

**To Reproduce**

A. GMH version v8.0.0.10 > 
1. battery protect mod: enabled and set to 94%
2. pms on screen-off : disabled
3. auto disable sync: enabled
4. quick-doze mod: enabled 80min

B. Steps to reproduce the behavior:
1. enable battery protect mod in galaxy max hz (mine is set to 94%)
5. disable samsung default battery protect setting
6. put the phone on the wireless charger
7. wait until it reach the percentage set in galaxy max hz and check if it will stop or not

**Expected behavior**
It's expected that the charge stops when reaching the desired percentage even when is charging wireless.
If you enable the original samsung battery protect setting it works even with the wireless charger, if you need to enable this settings it should be explained in the app, if you don't, it doesn't work as expected when charging wireless.

**Smartphone (please complete the following information):**
 - Model Number: SM-S908B
 - OS/OneUI version:  android13 OneUI5
 - Date of latest security update, if applicable: november 2022
 - Stock or modded ROM? stock

**Comment by tribalfs** [comment]
Thank you. Will check and fix it.

**Comment by tribalfs** [comment]
Please check this [build](https://github.com/tribalfs/GalaxyMaxHzPub/raw/main/french/gmh_v8.0.0.10_pbmwc_test.apk). Disable and reenable protect battery mod after installing.

**Comment by StefanoMarchesi** [comment]
Thank you, seems solved

Il Sab 26 Nov 2022, 18:15 tribalfs ***@***.***> ha scritto:
