### ISSUE TITLE
CQHD - Soft Reboot

### ISSUE THREAD

**Issue by LeeXDA21** [tribalfs/GalaxyMaxHzPub#72]
**Describe the bug**
When setting the resolution to CQHD, this initially works fine until the phone is rebooted, after the reboot the phone will do a soft reboot after around a minute, this is fixed by quickly setting the resolution to fhd, which shouldn't have to be done.

**To Reproduce**

A. Latest gmh installed, settings used:
120hz forced in psm.
AoD 48Hz
Auto disable sync

B. Steps to reproduce the behavior:
1. Set Resolution to CQHD
2. Reboot the phone.

**Expected behavior**
For the phone to boot properly and not do a soft reboot.

 - Model Number: G998B
 - OS/OneUI version: A13, Oui5
 - Date of latest security update, if applicable: November 22
 - Personal ROM.

**Comment by tribalfs** [comment]
Sorry, this is beyond control of the app or any resolution changer app.
App just applies the resolution using the api provided for android.
