### ISSUE TITLE
Sensors disabled on restart

### ISSUE THREAD

**Issue by Helloworld862** [tribalfs/GalaxyMaxHzPub#73]
Phone: samsung s20 ultra
Android version:13
Oneui 5
Version 8.0.0.11

After updating my phone to oneui 5 the 'auto sensor off' setting has been disabled but every time I restart my phone the phone boots with my sensors disabled and stays disabled until I turn the setting off on the quicklay menu manually.

Issue persists after removing galaxymaxhz

**Comment by tribalfs** [comment]
If it's GMH is uninstalled, then it's not GMH that causes it.
