### ISSUE TITLE
Donation error

### ISSUE THREAD

**Issue by AboAnas1902** [tribalfs/GalaxyMaxHzPub#74]
You paid $3.55 to Tribalfs

stc pay - Classic
VISA Credit Card
••••9433

Galaxy Max Hz Premium for:764dda93bdd9cd92:SM-S908E

Transaction ID: 7UL44185RW[0976826](tel:0976826)
Transaction made at 05:10:36 PM GMT+3

This is my PayPal Donation informations
I attached it because the Galaxy Max Hz app tells me that I didn't buy the pro version of the app, knowing that I actually bought it for the same device
I want a solution please
Thank you

**Comment by tribalfs** [comment]
If you performed factory reset on your device, you need to enter the activation code that was emailed to you to reactivate premium.
Please see [FAQ #2](https://github.com/tribalfs/GalaxyMaxHzPub/wiki/Frequently-Asked-Questions-(FAQs)#2-i-could-not-find-activation-code-email-in-my-inbox-or-i-forgot-to-backup-my-activation-code-what-should-i-do) for more info.

**Comment by AboAnas1902** [comment]
I don't have an activation code, I just bought it by PayPal
If you can help me find the activation code I would be thankful to you

في الأحد، 11 ديسمبر 2022, 8:33 ص tribalfs ***@***.***> كتب:

**Comment by tribalfs** [comment]
It was emailed to your paypal email account (she**.zana**20**@gmail.com)  when you bought it.

**Comment by tribalfs** [comment]
I resent it just now.
