### ISSUE TITLE
S22 ultra batery saving not keeping 120 hz one ui 5.0

### ISSUE THREAD

**Issue by DeadRace** [tribalfs/GalaxyMaxHzPub#79]
**Important: Before submitting a bug, ensure to check [FAQs](https://github.com/tribalfs/GalaxyMaxHzPub/wiki/FREQUENTLY-ASK-QUESTIONS-(FAQs))  and in the app description in the appropriate XDA forum thread for your device to ensure that the behavior is not expected or not part of the limitation of the app.**

**Describe the bug**

**To Reproduce**

A. GMH version and the exact settings in GMH

B. Steps to reproduce the behavior:

**Expected behavior**

**Screenshots**
If applicable, please include screenshots and/or [screen recording](https://play.google.com/store/apps/details?id=us.rec.screen) to help explain your problem. 

**Smartphone (please complete the following information):**
 - Model Number: [e.g. SM-S908B]
 - OS/OneUI version:  [e.g. android12 OneUI4.1]
 - Date of latest security update, if applicable: [e.g. June 2022]
 - Stock or modded ROM?

**Additional context**

**Crashlog**
If GMH crashes on your device, please include the crashlog of your device.  Just execute the following adb command.  Do this right after the crash (device must not be rebooted yet):
`adb logcat -b crash > crashlog.txt`
_Ctrl+C_ after 10seconds.
Then locate _crashlog.txt_ file in your adb installation folder then send it to tribalfs@gmail.com.

**Comment by tribalfs** [comment]
Please check [xda thread](https://forum.xda-developers.com/t/app-galaxy-max-hz-refresh-rate-mods-screen-off-mods-qs-tiles-tasker-support-and-more.4404929/#:~:text=Motion%20smoothness%20on,other%20workaround(s).).

**Comment by privacyguy123** [comment]
DeX workaround on Page 34 of your thread fixes issues. Even persists through "reload profiles."
