### ISSUE TITLE
Request for an updated profile

### ISSUE THREAD

**Issue by Narwhail** [tribalfs/GalaxyMaxHzPub#8]
The app is great but can't I switch between 90hz to 60 hz using the quick panel button? I have a Galaxy A22 5g and it only says in the profile that only 90hz is available or is this just my device's issue?

![Screenshot_20211201-011903_Settings.jpg](https://user-images.githubusercontent.com/95305951/144096912-55768b83-f3d1-47b8-9400-141b62212465.jpg)

![Screenshot_20211201-012453_Galaxy Max Hz.jpg](https://user-images.githubusercontent.com/95305951/144096937-489e378a-b7e3-4c55-bb22-7d15a000f511.jpg)

**Comment by tribalfs** [comment]
Modified profiles for Galaxy A22 on my backend. Try to reload profile now.
