### ISSUE TITLE
S22 Ultra stuck on 60hz in normal power mode

### ISSUE THREAD

**Issue by Jostian** [tribalfs/GalaxyMaxHzPub#80]
In normal power mode when using the slider to set default refresh rate to 10 to 96 hz in normal power mode, the phone stays only on 60hz or 10hz, no 96hz.

**To Reproduce**

A.8.0.0 see above

B. go to default refresh rate page and use slider to adjust NPM from 10 to 96hz  

**Expected behavior**
phone should go to 96hz when scrolling etc. but remains on 60hz or 10hz, never gets to 96hz

**Screenshots**

**Smartphone (please complete the following information):**
 - Model Number: SM-S908E
 - Android 13 UI 5
 - Dec 2022
 - Stock ROM

**Additional context**

**Crashlog**
If GMH crashes on your device, please include the crashlog of your device.  Just execute the following adb command.  Do this right after the crash (device must not be rebooted yet):
`adb logcat -b crash > crashlog.txt`
_Ctrl+C_ after 10seconds.
Then locate _crashlog.txt_ file in your adb installation folder then send it to tribalfs@gmail.com.

**Comment by tribalfs** [comment]
Please check [XDA thread](https://forum.xda-developers.com/t/app-galaxy-max-hz-refresh-rate-mods-screen-off-mods-qs-tiles-tasker-support-and-more.4404929/#:~:text=is%20enabled%20%5Bpremium%5D-,Note%3A%20Unfortunately%20this%20workaround%20is%20blocked%20and%20not%20working%20in%20OneUi5.0%20on%20S22%20Ultra%0APlease%20check%20this%20post%20for%20other%20workaround(s).,-Screen%2Doff%20Mods) for info.
