### ISSUE TITLE
German translation too long sometimes.

### ISSUE THREAD

**Issue by abucodonosor** [tribalfs/GalaxyMaxHzPub#82]
Hi, 

While playing with the per-app settings, I noticed
the German translation is way too long and overlaps
with the HZ values. See attached screenshot.
 
Everything works fine, it just looks strange.

![Screenshot_20221225_203358_Galaxy MaxHz](https://user-images.githubusercontent.com/18563759/209480348-f5ad3869-7c4b-43e9-8dcc-afe27cdb0c4d.jpg)

**Comment by tribalfs** [comment]
This is noted.
Can you suggest the shortened German translations for the following:
- Normal power mode  (in English we shortened it as NPM)
- Power saving mode  (in English we shortened it as PSM)
Thank you.

**Comment by tribalfs** [comment]
Fixed. Please download and manually install this [newer build](https://github.com/tribalfs/GalaxyMaxHzPub/releases/download/v8.0.0/galaxy_max_hz_v8.0.0.apk) .
Thank you.

**Comment by abucodonosor** [comment]
Thank you very much. It's fixed.

I try to find some time after the holidays and review the German translation. We have some ridiculous long words over here, but sometimes there may be alternatives.
