### ISSUE TITLE
App after update to Android 13 (Galaxy s20+)

### ISSUE THREAD

**Issue by Victorcassiano** [tribalfs/GalaxyMaxHzPub#83]
After updating the OS to Android 13 on my Galaxy 20+ I noticed that I can't use adaptive or normal 120hz on my device through the app, which I could do before the update.

I'm still analyzing the app after the OS update, I'll be bringing more questions soon.

Version: 8.0.0.12

**Comment by Victorcassiano** [comment]
I found what could have caused this.

Before activating the adaptive mode, you must turn off the battery saving mode and go to the device settings and leave the screen refresh rate in the default mode and then after that you can turn on the battery saving mode, open MaxHz and activate the mode adaptive that will work perfectly

**Comment by tribalfs** [comment]
Unfortunately the workaround to bypass 120Hz on PSM is already blocked in OneUi5.
What remains working is the extra step indicated in the app. Not very convenient but may be useful to you.
Thank you.
