### ISSUE TITLE
120hz not working on Power Saving - Android 13 One UI 5

### ISSUE THREAD

**Issue by ItzSebas10** [tribalfs/GalaxyMaxHzPub#86]
After One UI 5, the app stopped working for me and the option to keep the 120hz in Power Saving Mode is no longer working. I have a S21 Ultra.

**Comment by Mehdi-HS** [comment]
Same on Galaxy S20+, One UI 5

**Comment by tribalfs** [comment]
Hi!

Unfortunately, the bug that allow the app to bypass the 60Hz limit on PSM was already patched in OneUi5. 
Extra steps (indicated in the app) are now necessary for oneUi5; not very convenient but might help you.
No other known bypass yet.

https://forum.xda-developers.com/t/app-galaxy-max-hz-refresh-rate-mods-screen-off-mods-qs-tiles-tasker-support-and-more.4220481/#:~:text=%2DNote%3A%20It%27s%20reported%20that%20this%20workaround%20is%20blocked%20and%20not%20working%20in%20OneUi5.0%20on%20S21%20Ultra

https://forum.xda-developers.com/t/app-galaxy-max-hz-refresh-rate-mods-screen-off-mods-and-more.4190239/#:~:text=Motion%20smoothness%20on,in%20the%20app.
