### ISSUE TITLE
10hz mode on Galaxy S23

### ISSUE THREAD

**Issue by TheSloPro** [tribalfs/GalaxyMaxHzPub#94]
**Describe the bug**
_A clear and concise description of what the bug is._
I own a Galaxy S23+ (S916B). Its panel can go down to 10hz but only 24hz without this app (stock). When I select 10hz option it will go down to 10hz, even if I'm still touching the screen. This makes everything look laggy and unresponsive. [VIDEO](https://drive.google.com/file/d/1-75euptG8iiayJcxRo-y6Sh4MHjcrsbT/view?usp=sharing)

**To Reproduce**
GMH version: latest (v8.1.7) (all settings are in the video above ⬆️)

_Steps to reproduce the behavior:_
1. Go to "Default refresh rates"
2. Turn everything down to 10hz
3. Try to do anything on the phone and watch it not switch back to 120hz

**Expected behavior**
Switch to 120hz if:
- on screen - without touch
- touch detected

**Screenshots**
[This video](https://drive.google.com/file/d/1-75euptG8iiayJcxRo-y6Sh4MHjcrsbT/view?usp=sharing) wil better explain this bug.

**Smartphone (please complete the following information):**
 - Model Number: [SM-S916B]
 - OS/OneUI version:  [Android 13, OneUI 5.1]
 - Date of latest security update: [March 2023]
 - I'm rooted but I also noticed such behavior on completley stock ROM.

**Additional context**
I bought a licence for this app and was very satisfied on the previous phone - I had this app for at least a year and recetly upgraded to S23+ so if this bug can be fixed I'll hapilly pay for another device.

**Comment by TheSloPro** [comment]
I am currently rooted, for testing the app I'm all in, just hit me up in my DM!

**Comment by TheSloPro** [comment]
In other words:
24hz mode works fine - every time there is motion on screen or I'm touching it, it will be 120hz
On 10hz, it will go from 120 to 10 even if im touching it / there is motion. This is particularly visible when doing the back gesture.

**Comment by tribalfs** [comment]
Hi! It's due to[ limitation of the app ](https://github.com/tribalfs/GalaxyMaxHzPub/wiki/Frequently-Asked-Questions-(FAQs)#7-how-does-gmh-adaptive-mod-work)unable to detect continuous touch while on 10Hz mod. Unfortunately, there's no android api available to achieve it.
