### ISSUE TITLE
Per app setting doesn't show things it should

### ISSUE THREAD

**Issue by ir1descent** [tribalfs/GalaxyMaxHzPub#99]
For example, the screenshot editor on my Samsung is called:

com.samsung.android.app.smartcapture

this screen write/smart capture app is not in the app list. However, if you edit a backup (CSV) and add it manually, it just works fine. Forced 120hz for it now and it works

**Comment by tribalfs** [comment]
Please check v8.1.8 update.  Added option to show  apps with no launcher activity.
